Name: SystemMonitor
Version: 0.1.0
Link: http://www.webiny.com/store/webiny/system-monitor/
Description:

AuthorName: Webiny LTD
AuthorLink: http://www.webiny.com
AuthorEmail: info@webiny.com


Events:
    Core:
        Api:
            Before:
                - {Handler: \Apps\SystemMonitor\Php\Listeners\ApiListener::onBefore, Priority: 200}
            After:
                - {Handler: \Apps\SystemMonitor\Php\Listeners\ApiListener::onAfter, Priority: 200}