Name: SystemMonitor
Version: 1.0.0
Link: https://github.com/Webiny/SystemMonitor
Description: Monitor your server resources like CPU, disk usage and average load and easily analyze data using user friendly interface
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com

Events:
    Webiny:
        Api:
            Before:
                - {Handler: \Apps\SystemMonitor\Php\Listeners\ApiListener::onBefore, Priority: 200}
            After:
                - {Handler: \Apps\SystemMonitor\Php\Listeners\ApiListener::onAfter, Priority: 200}
